#ifndef QUICKNET_ALPHAS_H
#define QUICKNET_ALPHAS_H

#include "networknode.h"
#include "heap.h"
#include "bstreap.h"
#include "krapivsky.h"

#define DEFINE_HEADER_ALL(name)     \
  MAKE_KRAPIV_PREF_HEADERS(name) \
  MAKE_NODE_PREF_HEADER(name) \
  MAKE_HEAP_PREF_HEADERS(name)

DEFINE_HEADER_ALL(alpha_100)
DEFINE_HEADER_ALL(alpha_101)
DEFINE_HEADER_ALL(alpha_102)
DEFINE_HEADER_ALL(alpha_103)
DEFINE_HEADER_ALL(alpha_104)
DEFINE_HEADER_ALL(alpha_105)
DEFINE_HEADER_ALL(alpha_106)
DEFINE_HEADER_ALL(alpha_107)
DEFINE_HEADER_ALL(alpha_108)
DEFINE_HEADER_ALL(alpha_109)
DEFINE_HEADER_ALL(alpha_110)
DEFINE_HEADER_ALL(alpha_115)
DEFINE_HEADER_ALL(alpha_120)
DEFINE_HEADER_ALL(alpha_140)
DEFINE_HEADER_ALL(alpha_160)
DEFINE_HEADER_ALL(alpha_180)
DEFINE_HEADER_ALL(alpha_200)

#endif /* QUICKNET_ALPHAS_H */
