* Quicknet: Scalable Network Generator
  quicknet generates scale-free networks via preferential attachment
  (PA) models.  It is very fast; generating a network with n nodes
  is O(n log n), and networks with many millions of nodes can
  be generated in a few seconds on commodity hardware.

* Components
** quicknet/
   Use quicknet/ to generate networks from PA models.  There are a few
   example models already implemented (see price.c and krapivsky.c).
   See [[*Extending%20quicknet][Extending quicknet]] for a description of how to implement your
   own models.

** research/
   This directory contains the implementation for the paper "Efficient Network
   Generation under General Preferential Attachment"[fn:1].  This codebase
   made use of a lot of indirection to enable different central data
   structures; it is quite a bit more difficult to work with than
   quicknet/.  It is available for reference purposes.

* quicknet/
** Compiling quicknet
   #+begin_src sh
   cd quicknet
   make
   chmod 755 price krapivsky
   #+end_src
   
   This produces the 'price' and 'krapivsky' executables.
** Running quicknet
   #+begin_src sh
   ./price
   #+end_src
   or
   #+begin_src sh
   ./krapivsky
   #+end_src
** Extending quicknet
   Let modelx be the model you wish to implement.  In the quicknet/
   directery, create a file modelx.c which follows the same format as
   price.c and krapivsky.c.  Make the following changes to the
   Makefile:

   1. Append modelx.c to SRCS
   2. Append modelx.o to OBJS
   3. append modelx to EXE
   
   Then run
   #+begin_src sh
   make depend
   make modelx
   chmod 755 modelx
   #+end_src
   
   
   You should now have the executable modelx in the current directory.

   See the paper[fn:1] for a more detailed description of the data
   structures used in quicknet.

* Footnotes
[fn:1] James Atwood, Bruno Ribeiro, and Don Towsley. "Efficient
   Network Generation under General Preferential Attachment".  To be
   submitted to Simplex2014.

   
  
